data = {
    "Esc": "<b>Esc</b>: Closes TPT.",
    "F1": "<b>F1</b>: Shows the text displayed when you first open TPT, containing useful information",
    "F3": "<b>F3</b>: Toggles <a href=\"http://powdertoy.co.uk/Wiki/W/Debug_mode.html\">detailed view</a>.",
    "tilde": "<b>~</b>: Opens the <a href=\"http://powdertoy.co.uk/Wiki/W/Using_the_console.html\">developer console</a>.",
    "Tab": "<b>Tab</b>: Changes the brush type. <br> There are three built-in options (circle, square and triangle), but you can add your own with <a href=\"http://boxmein.net/glob/making-tpt-brushes.html\">custom brushes</a>.",
    "1": "<b>1</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Velocity_display\">Velocity display</a>. <br><b>Shift + 1 </b>: Set viewing mode to Life display, implying you have detailed mode enabled (D).",
    "2": "<b>2</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Pressure_display\">Pressure display</a>.",
    "3": "<b>3</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Persistent_display\">persistent display</a>.",
    "4": "<b>4</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Fire_display\">Fire display</a>.",
    "5": "<b>5</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Blob_display\">Blob display</a>.",
    "6": "<b>6</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Heat_display\">Heat display</a>.",
    "7": "<b>7</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Fancy_display\">Fancy display</a>.",
    "8": "<b>8</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Nothing_display\">Nothing display</a>.",
    "9": "<b>9</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Heat_gradient\">Heat gradient display</a>.",
    "0": "<b>0</b>: Sets viewing mode to <a href=\"http://powdertoy.co.uk/Wiki/W/Display_modes.html#Alternate_velocity\">Alternate velocity display</a>.",
    "equals": "<b>=</b>: Resets pressure.<br><b>Ctrl + equals</b>: Reset sparks.",
    "Q": "<b>Q</b>: Closes TPT.",
    "W": "<b>W</b>: Configures <a href=\"http://powdertoy.co.uk/Wiki/W/Gravity_modes.html\">Gravity Mode</a>.",
    "E": "<b>E</b>: Opens the Element search menu.",
    "R": "<b>R</b>: Dumps <em>every</em> drawn frame into the TPT folder, as a <a href=\"http://netpbm.sourceforge.net/doc/ppm.html\">PPM</a> image. Press R again to stop recording.<br><b>Ctrl+R</b>: Rotates a stamp before you place it.<br><b>Shift+R</b>: Flips a stamp horizontally before you place it.<br><b>Ctrl+Shift+R</b>: Flips a stamp vertically before you place it.",
    "Y": "<b>Y</b>: Configures <a href=\"http://powdertoy.co.uk/Wiki/W/Air_modes.html\">Air Modes</a>.",
    "U": "<b>U</b>: Toggles Ambient Heat.",
    "I": "<b>I</b>: Inverts all pressure (negative pressure becomes positive!)<br><b>Ctrl+I</b>: Install TPT (create file/URL associations)",
    "P": "<b>P</b>: Saves a screenshot into the powder directory, in the PNG format.",
    "lbrack": "<b>[</b>: Reduces the brush size. <br><b>Ctrl+[</b>: Reduce the brush size vertically.<br><b>Shift+[</b>: Decrease the brush size horizontally.",
    "rbrack": "<b>]</b>: Increases the brush size.<br><b>Ctrl+]</b>: Increase the brush size vertically.<br><b>Shift+]</b>: Increase the brush size horizontally.",
    "A": "<b>A</b>: Moves STK2 to the left, if they exist.",
    "S": "<b>S</b>: Allows you to select to create a stamp.<br>Spews STK2's element if they exist - in that case Ctrl+S creates a stamp.",
    "D": "<b>D</b>: Toggles <a href=\"http://powdertoy.co.uk/Wiki/W/Debug_mode.html\">detailed view</a> (also, developer or debug view).<br>Moves STK2 to the right if they exist - in that case Ctrl+D will toggle detailed view.",
    "F": "<b>F</b>: Moves forward for a single frame (cool for watching reactions or Game of Life in slow motion).",
    "G": "<b>G</b>: Enables the background grid. If the background grid is enabled, makes it bigger. <br><b>Shift+G</b>: Makes the background grid smaller, finally disabling it.<br><b>Ctrl+G</b>: Toggles Gravity Grid (shows little dots of gravity)",
    "H": "<b>H</b>: Toggle the HUD.<br><b>Ctrl+H</b>: Shows the help text when you first open TPT.",
    "K": "<b>K</b>: Show all stamps.",
    "L": "<b>L</b>: Load the last-used stamp.",
    "Z": "<b>Z</b>: Holding Z will let you look around with the zoom window. <br>Click while holding Z to place the zoom window to a location.<br>Scroll up or down while holding Z to adjust the zoom level.<br><b>Ctrl+Z</b>: Undo (limited).",
    "X": "<b>Ctrl+X</b>: Cut",
    "C": "<b>Ctrl+C</b>: Copy",
    "V": "<b>Ctrl+V</b>: Paste",
    "B": "<b>B</b>: Show the decoration editor. <br><b>Ctrl+B</b>: Toggle decorations.",
    "N": "<b>N</b>: Toggle Newtonian Gravity.",
    "spacebar": "<b>Space</b>: Pause and unpause the game.",
    "semicolon": "<b>;</b>: Toggle Replace mode. <br><b>Ctrl+;</b>: Toggle Specific Delete mode.",
    "Insert": "<b>Insert</b>: Toggle Replace mode.",
    "Delete": "<b>Delete</b>: Toggle Specific Delete.",
    "Ctrl": "<b>Ctrl</b>: Modifies other keys.<br>Holding Ctrl and click-dragging lets you create boxes.",
    "Shift": "<b>Shift</b>: Modifies other keys.<br>Holding Shift and click-dragging lets you create lines.<br>Holding Shift, clicking on a fan-wall and dragging lets you set the fan's direction and strength.",
    "Alt": "<b>Alt</b>: Modifies other keys.<br>Holding Alt and clicking lets you instantly pick another element to draw.",
    "arrow-left": "<b>&larr;</b>: Moves STKM left. <br>Nudges stamps left before placing them.",
    "arrow-right": "<b>&rarr;</b>: Moves STKM right. <br>Nudges stamps right before placing them.",
    "arrow-up": "<b>&uarr;</b>: Makes STKM jump. <br>Nudges stamps up before placing them.",
    "arrow-down": "<b>&darr;</b>: Makes STKM spew its element. <br>Nudges stamps down before placing them.",
    "invalid": "Not a key!"
};
